name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "temurin"
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sdkmanager --install "platforms;android-28" "build-tools;28.0.3"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --refresh-dependencies :onebusaway-android:assembleAgencyYGoogleDebug --stacktrace

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: agency-y-google-debug-apk
          path: |
            onebusaway-android/build/outputs/apk/**/*.apk
